spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/shop
    username: postgres
    password: 123
    driver-class-name: org.postgresql.Driver
  jpa:
    database: postgresql
    show-sql: true
#    properties:
#      hibernate:
#        format_sql: true
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yml
  cache:
    cache-names: "exchangeCache,userLoginCache"
    caffeine:
      spec: maximumSize=1,expireAfterWrite=1m
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: event-group-double
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
scheduler:
  enabled: false
  period: PT30S
app:
  file-names:
    exchange-rate: "src/main/resources/parameters/ExchangeRate.json"
  currency:
    url: "${EXCHANGE_SERVICE_URL:http://localhost:8081}"
    url-get-currency: "/api/v2/exchange"
  tax:
    url: "${TAX_SERVICE_URL:http://localhost:8082}"
    url-get-tin: "/api/v3/users"