spring:
  datasource:
    url: jdbc:h2:mem:shop;MODE=PostgreSQL
    driver-class-name: org.h2.Driver
    username: sa
    password: ""
  jpa:
    database: h2
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yml
  h2:
    console:
      enabled: true
  cache:
    cache-names: "exchangeCache,ordersCache"
    caffeine:
      spec: maximumSize=1,expireAfterWrite=1m
  kafka:
    bootstrap-servers: "${SPRING_KAFKA_BOOTSTRAP_SERVERS:localhost:9092}"
    consumer:
      group-id: event-group-double
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer


scheduler:
  enabled: false
  period: PT30S
app:
  file-names:
    exchange-rate: "src/main/resources/parameters/ExchangeRate.json"
  currency:
    url: "${EXCHANGE_SERVICE_URL:http://localhost:8081}"
    url-get-currency: "/api/v2/exchange"
  tax:
    url: "${TAX_SERVICE_URL:http://localhost:8082}"
    url-get-tin: "/api/v3/users"