spring:
  datasource:
    url: jdbc:h2:mem:shop;MODE=PostgreSQL
    driver-class-name: org.h2.Driver
    username: sa
    password: ""
  jpa:
    database: h2
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yml
  h2:
    console:
      enabled: true
