spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/shop
    username: postgres
    password: 123
    driver-class-name: org.postgresql.Driver
  jpa:
    database: postgresql
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yml
  cache:
    cache-names: "exchangeCache"
    caffeine:
      spec: maximumSize=1,expireAfterWrite=1m
scheduler:
  enabled: true
  period: PT30S
app:
  file-names:
    exchange-rate: "src/main/resources/parameters/ExchangeRate.json"
